# Generated by Django 5.2 on 2025-05-05 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meals', models.CharField(choices=[('F', 'Fruits'), ('N', 'Nuts'), ('L', 'Leaves')], default='F', max_length=1)),
                ('monkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.monkey')),
            ],
        ),
    ]
