# Generated by Django 5.2 on 2025-05-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_feeding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ['-date']},
        ),
    ]
