# Generated by Django 5.2 on 2025-05-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='monkey',
            name='toys',
            field=models.ManyToManyField(to='my_app.toy'),
        ),
    ]
